export enum UserRole {
  SUPER_ADMIN='SUPER_ADMIN',
  ADMIN = 'ADMIN',
  FINANCE = 'FINANCE',
  ACCOUNTANT = 'ACCOUNTANT',
  HELPDESK='HELPESK',

  MERCHANT = 'MERCHANT',
  DEVELOPER = 'DEVELOPER',
  AGENT = 'AGENT',
  CUSTOMER='CUSTOMER'
  }